### ISSUE TITLE
часть 3, please? ) 

### ISSUE THREAD

**Issue by AndriyKalashnykov** [zhivulinal/react-apollo-gqlgen-tutorial#1]
можно ли надеяться на часть 3 (в скором времени?)
и да, это чуть ли не единственный толковый обучающий материал в данном направлении адресующий реальные проблемы (сессии и авторизацию)

**Comment by zhivulinal** [comment]
Привет!
К сожалению, сейчас нет времени для продолжения. Возможно, займусь этим в декабре - январе.
